# Generated by Django 4.1.3 on 2022-12-17 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postscomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postscomment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата комментария'),
            preserve_default=False,
        ),
    ]
