# Generated by Django 4.1.3 on 2022-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_architect_description_archstyle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Дата постройки'),
        ),
    ]
