# Generated by Django 4.1.3 on 2022-11-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='street',
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.ManyToManyField(blank=True, related_name='building_street', to='buildings.street', verbose_name='Улица'),
        ),
    ]
