# Generated by Django 4.1.3 on 2022-11-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_remove_building_street_building_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingcomment', verbose_name='Родитель'),
        ),
    ]
