# Generated by Django 4.1.3 on 2022-12-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_buildingcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='archstyle',
        ),
        migrations.RemoveField(
            model_name='building',
            name='category',
        ),
        migrations.AddField(
            model_name='building',
            name='archstyle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_archstyle', to='buildings.archstyle', verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_archstyle', to='buildings.category', verbose_name='Категория'),
        ),
    ]
