# Generated by Django 4.1.3 on 2022-12-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_remove_building_archstyle_remove_building_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='archstyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_archstyle', to='buildings.archstyle', verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='building',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_archstyle', to='buildings.category', verbose_name='Категория'),
        ),
    ]
