# Generated by Django 4.1.3 on 2022-12-17 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('buildings', '0008_alter_building_archstyle_alter_building_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingcomment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата комментария'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingcomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='users.profile'),
        ),
    ]
